### ISSUE TITLE
PHP Notice:  Trying to get property 'id' of non-object in .../cryptowoo-monero-addon.php on line 455

### ISSUE THREAD

**Issue by Wegerich** [WeProgramIT/cryptowoo-monero-addon#18]
[19-Feb-2020 01:01:56 UTC] PHP Notice:  Trying to get property 'id' of non-object in /home/user/public_html/wp/wp-content/plugins/cryptowoo-monero-addon/cryptowoo-monero-addon.php on line 455

I've had this notice in the logs a couple of times recently. Not sure what it relates to.

**Comment by Olsm** [comment]
This is probably happening because your cron jobs some times reach the block scan timeout in seconds. You may want to increase the block scan timeout seconds option to a bit higher to ensure all blocks are scanned when as I remember you got a long delay between block scans. But either way we should get this PHP notice fixed, although it is not a critical issue and cause nothing to break other than unnecessarily filling logs.

For your info you should also see this message in your logs for the orders that ended up with this timeout: "Block scan timeout reached for order ..." But you will only see this in the log if you have set to log level "debug".

Please see if the last Commit I referenced here will fix the issue for you. Then please set CryptoWoo debugging to log level "debug", increase the block scan timeout seconds setting until you see no more debug messages in the log file such as "Block scan timeout reached for order..." To ensure smooth order processing, but not so much that you will reach php timeouts in your server.

Please confirm that this issue is solved.

**Comment by Wegerich** [comment]
Thanks, I uploaded the commit. I changed the block scan timeout limit from 10 seconds to 15 seconds. I will let you know if the error continues to occur.
